### ISSUE TITLE
Fine-tuning TransCoder

### ISSUE THREAD

**Issue by wasiahmad** [facebookresearch/CodeGen#12]
Hi,

We recently proposed a small-scale program translation dataset, called [AVATAR](https://github.com/wasiahmad/AVATAR). We want to fine-tune TransCoder on the translation task but we didn't find any documentation on that. Can you provide some guidelines on fine-tuning TransCoder?

**Comment by brozi** [comment]
Hi,
Since you have a parallel dataset, you probably want to finetune using the MT objective. 
If you have two languages lang1 and lang2, you need to add this to the arguments when training 
```
--mt_steps 'lang1-lang2,lang2-lang1`
``` 
For the dataset, you need .pth files with this format (assuming the string lang1 is < lang2 in lexicographical order): `train.lang1-lang2.lang1.pth` and `train.lang1-lang2.lang2.pth` or files with `.i.pth` if you are training on several GPUs. You can use the preprocessing pipeline to create the dataset and just add the right symbolic links in the end.

**Comment by wasiahmad** [comment]
To confirm, the `.pth` files should contain BPE processed dataset (not just the tokenized dataset)?

**Comment by brozi** [comment]
- Yes the .pth should contain the binarized BPE processed dataset. 
- For the pipeline, the monolingual functions mode will also break your data into functions and I'm not sure that would work for your usecase. It seems like you got your parallel dataset from competitive programming websites so even though the files are parallel I guess the functions in the files will not necessarily be parallel.
You can try the monolingual mode but if you encounter errors for some of your examples you may need to modify it a bit to ensure that you don't skip lines (without outputting anything in the .tok file) otherwise you may have mismatching elements in your python and java files...
Since your dataset is small and you may already have done a train-test split, you probably want to generate the train/valid/test tokenized files yourself and run the pipeline after commenting these lines https://github.com/facebookresearch/CodeGen/blob/master/codegen_sources/preprocessing/preprocess.py#L86-L93. You could also just import and run the functions to apply a BPE model and binarize the data in a notebook or a small script.
Don't forget to use the BPE model that we provide if you want to reload our model to finetune it.
- The TransCoder model uses fast_bpe. The DOBF models we link to in [DOBF's ReadME](https://github.com/facebookresearch/CodeGen/blob/master/docs/dobf.md) use the roberta_bpe and the architecture of RoBERTa in order to make it comparable to CodeBERT and graphCodeBERT on downstream tasks. However we also trained a model with a fast bpe and the same architecture as TransCoder which I could also link to at the end of this ReadME.

PS: since your dataset contains only python and java code, you will probably get better results using the model we pre-trained using DOBF and which we linked in [TransCoder's ReadME](https://github.com/facebookresearch/CodeGen/blob/master/docs/transcoder.md#release): [translator_transcoder_size_from_DOBF](https://dl.fbaipublicfiles.com/transcoder/pre_trained_models/translator_transcoder_size_from_DOBF.pth)
It uses the same architecture and BPE as TransCoder.

**Comment by wasiahmad** [comment]
Awesome! We used your TransCoder-DOBF model in our experiments.

We extracted functions from the programs we collected from G4G and only considered programs having 1 standalone function. We fine-tuned the baseline models and now want to do the same with TransCoder. So far, we have been considering TransCoder without fine-tuning. You can see the comparison between TransCoder (w/o fine-tuning) and other models [here](https://github.com/wasiahmad/AVATAR/tree/main/evaluation#evaluation-results).

Although not related to this discussion thread, I want to take your input on one thing. It may sound a bit weird to you.

We used the previous repo of [TransCoder](https://github.com/facebookresearch/TransCoder) and got higher Computational Accuracy on the G4G dataset proposed in the TransCoder paper. But when I switched to the new codebase which is this repo, the performance dropped significantly. We used beam_size=5 (top 1) in our experiment. Did you notice any difference with your new codebase? I do not see any difference in tokenization or BPE encoding. However, I saw many changes were made to include DOBF in the source code.

Here are the performances (`beam_size=5 (top 1)`):

TransCoder (using old repo) - Java to Python: 49.6% ; Python to Java: 35.1%
TransCoder (using this repo) - Java to Python: 41.2% ; Python to Java: 28.8%

Any help/pointer would be appreciated.

**Comment by brozi** [comment]
Ok cool. I assumed you were using the model from the first version of TransCoder since DOBF wasn't cited in your paper on arxiv but I guess you will update it at some point. 

About your issue with the scores using the old repo vs this repo, it definitely shouldn't be happening, you should get almost exactly the same scores (except for the timeouts) with the old and the new repo if you are evaluating with the same model. The tokenization should be almost the same and the BPE encodings exactly the same, however the binarization should be different since we reserve 500 tokens extra tokens for the identifier tokens in the new version. 
A few things to check:
- check that you are reloading the encoder and the decoder correctly in the logs (search for `============ Model Reloading`).
- check the detailed computational accuracy results. Especially that the total number of examples and number of script_not_found is the same on both sides for the same metric and that the number of timeouts didn't blow up (that could be due to external factors on your server)
- which command are you using to run the evaluation on each repo? Are they the same?
- You may want to run the evaluation with beam_size=1 on both sides and check that the results are the same as in the results table of the paper corresponding to your model. Which model did you use exactly ?

**Comment by wasiahmad** [comment]
Yes, we didn't include the updated result in the archived paper. Previously, we were using `model_1.pth and model_2.pth` and now we are using the models shared [here](https://github.com/facebookresearch/CodeGen/blob/master/docs/transcoder.md#pre-trained-models).

I am using the `translate.py` file to perform the translation, therefore I guess there should be no issue regarding binarization. I actually made some adjustments in the code to serve my need and it was working fine till I was using model implementations from the old repo. After using the model implementation from the new repo, the performance drops. I checked for potential bugs but couldn't find any.

I checked `identical_gold`, `failure`, `total_evaluated` and they are roughly the same. The major difference is in `error` and in `success`. I did some analysis too based on error types. For example, in Java to Python translation:


#### [THIS REPO]
```
{   
    "AttributeError": 11,
    "IndexError": 18,
    "KeyError": 13,
    "NameError": 16,
    "RecursionError": 3,
    "SyntaxError": 36,
    "TypeError": 63,
    "UnboundLocalError": 10,
    "ZeroDivisionError": 1,
    "other": 11,
    "total": 182
}
```

#### [OLD REPO]
```
{   
    "AttributeError": 12,
    "IndexError": 18,
    "KeyError": 10,
    "NameError": 18,
    "RecursionError": 1,
    "SyntaxError": 11,
    "TypeError": 51,
    "UnboundLocalError": 9,
    "ZeroDivisionError": 0,
    "other": 12,
    "total": 142
}
```

As you can see, `SyntaxError` and `TypeError` increased with the use of code from this repo. You can find how we categorized the errors [here](https://github.com/wasiahmad/AVATAR/blob/main/evaluation/TransCoder/classify_errors.py).

Let me run the evaluation with `beam_size=1` and see how the model performs.

**Comment by wasiahmad** [comment]
#### The following results are using the code from this repository.

Results with beam_size=1:

Java to Python: **40.3%** [comparing to 41.2% with beam_size=5 (top 1)]
Python to Java: **27.2%** [comparing to 28.8% with beam_size=5 (top 1)]

The numbers reported in the TransCoder paper are:

Java to Python: **35.0%**
Python to Java: **24.7%**

Seems like we are getting comparable performance, but I am not sure why then I got higher numbers using the old repository.

**Comment by brozi** [comment]
I ran the evaluation again on a clean repository and I'm getting higher computation accuracies than you on TransCoder's test set. With these models I'm getting higher scores than in the TransCoder paper with beam_size 1 and slightly lower scores with beam size 10. After writing the TransCoder paper, we solved a few detokenization bugs in the code so that could explain why the current version is better with beam size 1 but I don't know why the scores are lower with the beam size 10 (top 1) metric. I will need to investigate it further, I'm suspecting that our new tokenizer (based on tree-sitter instead of javalang) leads to slightly different tokenization in a few cases. 

It is also surprising that your scores are lower than mine using the new repository. I looked at the code of `translate.py` and didn't find any bug, but there may be some differences in the way you perform the evaluation if you're not using our methods to do it. Using the train.py script, which calls evaluator.py would also be more efficient. We were thinking of `translate.py` as a small tool for demos and didn't optimize it as much as the rest (for instance it processes the data on the fly and doesn't batch the calls to generate translations). 

PS: I ran it without the `--retry_mismatching_types` argument to make it faster while the results in the paper were obtained with this argument turned on. It uses a few heuristics to cast the input types to the right types and avoid type errors in cases when they are easy to avoid and can increase the score a little bit but it couldn't explain the differences we're seeing here. 

**beam size = 1:**
Java to Python (TransCoder_model_1): 44.49 %
Python to Java (TransCoder_model_2): 32.64%

**beam size = 10 (top 1)**
Java to Python (TransCoder_model_1): 46.44 %
Python to Java (TransCoder_model_2): 36.0%

**Comment by wasiahmad** [comment]
Thanks a lot for doing the evaluation on your end. Since I need to fine-tune TransCoder, I fully migrate your codebase to perform the experiments, hopefully, I will get the results you mentioned.

I am particularly clueless because I can reproduce most of your results reported in the TransCoder paper with your old codebase (using translate.py). When I moved to the new codebase, I carefully adopted the code portion I needed. As I was able to successfully run experiments, I thought everything was ok. But with the new code, I have always observed degraded performances, and also with beam decoding performances didn't improve much.

**Comment by brozi** [comment]
Yes sorry about that, we tried to make the migration easier than that. 
To be honest, I don't know why you got such a low score using `translate.py` and I wouldn't have expected you to get a lower score when using the new repository and the new version of the model. 
Could you give me an example of input function that fails with the new codebase and succeeded with the previous codebase and with the output that failed ? I would try to reproduce the error and to understand what's happening.

**Comment by wasiahmad** [comment]
I adapted the whole source code of the new repo now and still getting the same performance. I guess we are operating on different input files. To confirm, I am using the `transcoder_test.java.tok` and `transcoder_test.python.tok` files from [transcoder_test_set.zip](https://dl.fbaipublicfiles.com/transcoder/test_set/transcoder_test_set.zip). 

While I used translate.py, I do not use any tokenization, only use BPE apply and then perform translation. Save it in a file and then perform the evaluation. Do you think that is okay to use the preprocessed tokenized files provided in this repo?

**Comment by wasiahmad** [comment]
@brozi can you provide a complete example of a command for fine-tuning Transcoder-DOBF on translation task? 

- What should be the format of the files in `data_path`? 
- I want to fine-tune using 1 GPU with max 2048 tokens and use gradient_accumulation to have a batch size of 16 or 32. For validation, I want to use BLEU and am not sure what I should use for `--validation_metrics`. Can you suggest the flags accordingly?
- What should I set to `split_data_accross_gpu` if using 1 or multiple GPUs in the same machine?

I guess the following flags I need to use for the translation task.

```
--mt_steps 'java-python,python-java' \
--encoder_only False \
--n_layers 0  \
--n_layers_encoder 12  \
--n_layers_decoder 6 \
--emb_dim 768  \
--n_heads 12  \
--lgs 'java-python' \
--max_vocab 64000 \
--gelu_activation true \
--roberta_mode true
```

**Comment by brozi** [comment]
> I adapted the whole source code of the new repo now and still getting the same performance. I guess we are operating on different input files. To confirm, I am using the `transcoder_test.java.tok` and `transcoder_test.python.tok` files from [transcoder_test_set.zip](https://dl.fbaipublicfiles.com/transcoder/test_set/transcoder_test_set.zip).

The new evaluation I ran was from the .pth files in this zip. I double checked and they correspond exactly to the .tok files.

> While I used translate.py, I do not use any tokenization, only use BPE apply and then perform translation. Save it in a file and then perform the evaluation. Do you think that is okay to use the preprocessed tokenized files provided in this repo?

Yes you should be getting **exactly** the same input as me when I ran the evaluation again if you just apply a fastBPE with the codes in data/bpe/cpp-java-python/codes on each line in the `transcoder_test.java.tok` and `transcoder_test.python.tok` files. 


The structure of your files seems fine if you don't want to split your data across GPUs (they will all read from the same file here).
I can see a few issues with your command: 
- `--reload_model "$MODEL_PATH,"` reloads only the encoder and initializes the decoder randomly. I think that for your usecase you'd rather use `--reload_model "$MODEL_PATH,$MODEL_PATH"` to reload both.
- TransCoder doesn't use gelu activations so you should probably remove `--gelu_activation true` or set it to false (default value). 

Suggestions:
- TransCoder uses `--n_heads 8` and you use `--n_heads 16`. The extra heads will just be initialized randomly and it shouldn't really be an issue, just be aware that there will be some warnings about the extra weights not being found in the checkpoint when you reload the model 
- For machine translation, we generally use `--tokens_per_batch` to choose the batch size for each batch so that the total number of tokens in the batch is close to `--tokens_per_batch` and it would probably be more efficient for you to do the same. Try `--tokens_per_batch 5000` for instance if you have 32GB GPUs.
- if you're evaluating on TransCoder's validation and test datasets, it would probably be nice to compute the computational accuracy by adding `--eval_computation True`

You should also check if there are any warnings when you reload the model (e.g. if the lang embeddings and weights are loaded correctly). Maybe search for "random" in the logs to check that nothing was initialized randomly.
Here is the number of parameters in transcoder, I guess the difference comes from the extra attention heads
```
INFO - 08/31/21 06:21:05 - 0:00:18 - Number of parameters (encoder): 143279616
INFO - 08/31/21 06:21:05 - 0:00:18 - Number of parameters (decoders): 168482304
```

**Comment by wasiahmad** [comment]
With `n_heads=8`, I get this (which does not match your number):

```
INFO - 09/01/21 11:20:06 - 0:00:15 - Number of parameters (encoder): 143278592
INFO - 09/01/21 11:20:06 - 0:00:15 - Number of parameters (decoders): 168481280
```

Can you clarify what is the values of the following flags for `TransCoder` and `translator_transcoder_size_from_DOBF`?

```
--n_layers_encoder ?  \
--n_layers_decoder ? \
--emb_dim ? \
--n_heads ? \
```

**Comment by brozi** [comment]
We probably have the same parameters. I was just comparing to a model running on C++ as well so the extra parameters were the lang embeddings for C++. I checked and we have the same number of parameters when I run transcoder on only two languages. 
```
--n_layers_encoder 6  \
--n_layers_decoder 6 \
--emb_dim 1024 \
--n_heads 8 \
```

**Comment by wasiahmad** [comment]
Thanks a lot, @brozi for all your co-operation. I have tuned TransCoder and see the Java-to-Python translation performance improves from 44% to 61% (beam size 1) after fine-tuning on your dataset (I need to optimize for more epoch). However, I have still the issue that using my modified script `translate.py` gives me a much lower score than you (almost 5 points difference). I have carefully checked the data and strongly believe there is no issue. 

I think I am going to run experiments with both old and new code and report performances. Otherwise, I am unable to find problems in any of the codebases.

**Comment by wasiahmad** [comment]
I have a quick question. I saw in the documentation that to train TransCoder from a pre-trained model, you have set:

```
--epoch_size 50000  \
--max_epoch 10000000  \
```

Aren't these numbers too large? I want to confirm, `epoch_size` means after how many optimization steps, validation will be performed and `max_epoch` means for total epochs. Also, if I set batch_size to 4 and accumulate_gradients to 4 and epoch_size to 2000, does it mean that after 2000 optimization steps (with batch size 16), validation will be performed? Please shed light on these notions, currently it is difficult to understand them from the codebase.

**Comment by wwnew** [comment]
@wasiahmad I have a question. how could I get all those files?
```
test.java-python.bpe.java    test.java-python.python.pth    train.java-python.java.pth    valid.java-python.bpe.python
test.java-python.bpe.python  train.java-python.bpe.java     train.java-python.python.pth  valid.java-python.java.pth
test.java-python.java.pth    train.java-python.bpe.python   valid.java-python.bpe.java    valid.java-python.python.pth
```

**Comment by brozi** [comment]
> Thanks a lot, @brozi for all your co-operation. I have tuned TransCoder and see the Java-to-Python translation performance improves from 44% to 61% (beam size 1) after fine-tuning on your dataset (I need to optimize for more epoch). However, I have still the issue that using my modified script `translate.py` gives me a much lower score than you (almost 5 points difference). I have carefully checked the data and strongly believe there is no issue.
> 
> I think I am going to run experiments with both old and new code and report performances. Otherwise, I am unable to find problems in any of the codebases.

Hum I really don't understand what's happening. One difference between your pipeline and mine is that I'm running with max_len=512 so I'm removing 8 elements from the training dataset. However only the first one (DYNAMIC_PROGRAMMING_SET_37_BOOLEAN_PARENTHESIZATION_PROBLEM) has some unit tests so the difference for the computational accuracy should be very small. Lines and ids that we remove.
```
[(95, 'DYNAMIC_PROGRAMMING_SET_37_BOOLEAN_PARENTHESIZATION_PROBLEM'),
 (116, 'CONVERTING_DECIMAL_NUMBER_LYING_BETWEEN_1_TO_3999_TO_ROMAN_NUMERALS'),
 (167, 'PRINT_EQUAL_SUM_SETS_ARRAY_PARTITION_PROBLEM_SET_2'),
 (295, 'MID_POINT_CIRCLE_DRAWING_ALGORITHM'),
 (313, 'MAXIMUM_POINTS_COLLECTED_BY_TWO_PERSONS_ALLOWED_TO_MEET_ONCE'),
 (415, 'COUNT_WAYS_INCREASE_LCS_LENGTH_TWO_STRINGS_ONE'),
 (540, 'FIND_SIZE_OF_THE_LARGEST_FORMED_BY_ALL_ONES_IN_A_BINARY_MATRIX'),
 (848, 'PROGRAM_DISPLAY_ASTROLOGICAL_SIGN_ZODIAC_SIGN_GIVEN_DATE_BIRTH')]```
```

However, looking at the detailed errors you sent earlier, I guess there may be some discrepancy between the examples we evaluate. You say you have 182 errors in total for Java -> Python for a score of 35%(I'm assuming using the model 1) while I have  257 for a score of 44.9% using the model 1. Here are my detailed results, do you have the same number of functions matched to a unit test ? (except for DYNAMIC_PROGRAMMING_SET_37_BOOLEAN_PARENTHESIZATION_PROBLEM if you don't remove it).
```
{"error": 165, "failure": 89, "identical_gold": 17, "script_not_found": 477, "success": 206, "timeout": 3, "total": 940, "total_evaluated": 463}
```

For your question about the epochs: 
Yes the number of epochs is very large. It basically means that the number of epochs is virtually unlimited and in practice we use something like `--stopping_criterion "valid_java_sa-python_sa_mt_comp_acc,25"` or monitor the model by hand to stop it when it converges or after a given amount of time.
For the epoch size: it is important to set it to a relatively large value when evaluating the computational accuracy since this metric takes some time to compute and you don't want to spend most of your time evaluating the model. 

>[Note] I found some bugs in the current codebase.
>In this line, we should use self.epoch_size = len(self.data).
>It seems like warmup_updates cannot be 0 (it gives ZeroDivisionError at model/src/optim.py line 126).

Thank you very much for signaling these, I'll solve these bugs.

**Comment by wasiahmad** [comment]
On my end, I always see:

```
# Java to Python
"total_evaluated": 464
"total": 942
``` 

Detailed breakdown (error, failure, success, timeout) is listed [here](https://github.com/wasiahmad/AVATAR/tree/main/evaluation#evaluation-results). Note that, these are based on all new models (e.g., `TransCoder_model_1.pth`). I guess in my case max_len=512 too since we have a condition in `translate.py` that is: `int(min(self.reloaded_params.max_len, 3 * len1.max().item() + 10))`.

By the way, you get 257 errors for a score of 44.9% using model 1, then you probably have fewer failure cases I believe. We compute `comp_acc` as `success/total_evaluated` and I ensured:

```
total_evaluated = error + failure + success + timeout
```

Am I missing something?

**Comment by wasiahmad** [comment]
> @wasiahmad I have a question. how could I get all those files?
> 
> ```
> test.java-python.bpe.java    test.java-python.python.pth    train.java-python.java.pth    valid.java-python.bpe.python
> test.java-python.bpe.python  train.java-python.bpe.java     train.java-python.python.pth  valid.java-python.java.pth
> test.java-python.java.pth    train.java-python.bpe.python   valid.java-python.bpe.java    valid.java-python.python.pth
> ```

The answer of your question is here: https://github.com/wasiahmad/AVATAR/blob/main/transcoder/prepare.sh.

**Comment by wasiahmad** [comment]
@brozi I saw you have a pull request where you have solved the issue of warmup_updates=0. But I think you forgot to update the decay_factor too. 

```
self.decay_factor = warmup_end_lr * warmup_updates ** self.exp_factor
```

When warmup_updates=0, decay_factor would become 0 too. I guess a fix for warmup_updates=0 would be:

```
self.lr_step = (
            (warmup_end_lr - warmup_init_lr) / warmup_updates
            if warmup_updates > 0 else 1
        )
self.decay_factor = (
            warmup_end_lr * (warmup_updates ** self.exp_factor)
            if warmup_updates > 0 else warmup_end_lr
        )
```

So, when warmup_updates=0, the learning rate would just decay proportionately to the inverse square root of the update number: `lr = warmup_end_lr * (num_updates ** -0.5)`.

**Comment by brozi** [comment]
Thanks @wasiahmad. That's right and I also think that will fix it. 

You total_evaluated seems right (I have 463 instead because we removed one example with tests which has more than 512 tokens). I was under the impression that you had less errors than that because of one of your previous replies.
It seems like I can't reproduce your bug. I get very consistent results when running translate.py on the TransCoder repo and on this one. 
The output of the model was slightly different on only 6 files (3 with unit tests) due to the constant [LAYER_NORM_EPSILON](../codegen_sources/model/src/model/transformer.py#L17) being `1e-5` instead of `1e-12` in the transcoder repository but that can't explain your score. 

I will stop investigating translate.py since I can't reproduce your bug on my end with the version of that file that is currently in this repository.
Here is a pickle containing my results translating with `translate.py` and this repo in case you want to compare it to what you obtained. It's a list of tuples `(sample_id, detokenized_result, x1 (model input), x2 (model output))` https://dl.fbaipublicfiles.com/transcoder/data/result_translate_sentences.pkl

PS: Since the BPE model is the same as for the previous repo and the tokenization should return the same thing, you should be getting the same results with the input dataset you were using with the previous repo.

**Comment by wasiahmad** [comment]
Thanks, @brozi, you really did a lot to help me, I really appreciate it. 

I have shared both my adapted translation code with the old repo (TransCoder one) and this repo [here](https://github.com/wasiahmad/AVATAR/tree/main/transcoder). The script `run.sh` and `run_v0.sh` are using new repo and old repo, respectively.

I am working to compare them. I see the differences are not in tokenization, bpe_apply, or binarization. The issue could be either in model implementation, decoding params, or the pre-trained models. Note that, in the old code, we use `model_1.pth`  (java->python) and `model_2.pth` (python->java).

I have the following results with the new repository codebase (w/ beam_size=5). 

![Screen Shot 2021-09-02 at 1 12 43 PM](https://user-images.githubusercontent.com/17520413/131895431-1170a406-a745-4017-b776-6434bcc59ed8.png)

I am still looking for a ~4-5 points boost as you mentioned.

**Comment by wasiahmad** [comment]
Closing this issue as the problem seems solved, I can now get the same result with code from both repositories. I don't know how the problems were solved (yeah it sounds silly) but I made the translate.py from both codebases as close as possible. Both the scripts are available [here](https://github.com/wasiahmad/AVATAR/tree/main/transcoder).

The results that I get now using beam_size=5 are as follows.

![Screen Shot 2021-09-02 at 10 46 08 PM](https://user-images.githubusercontent.com/17520413/131947626-5f8db8e2-408b-4e93-999a-3ae9445f3988.png)

I would like to say, thank you so much @brozi :two_hearts:.

**Comment by brozi** [comment]
Nice! The performance boost looks really good in both directions. I'm not too surprised that even a few parallel exemples help a lot, especially since the domain should be quite similar to that of our test set (small algorithmic functions scrapped from geeksforgeeks). I guess you did something to remove the functions that are the same or almost the same as those in the test set from your train set ? 

About the the 4-5 points you're missing, I'm afraid I don't know what's happening. I double check and ran `translate.py` for java -> python with the CodeGen and the TransCoder repos. I got the same model outputs when changing the epsilon parameter of the layernorm I mentioned above and only slightly different results otherwise (it cannot explain a 4% pts difference). `model_1.pth` and the new model 1 given in this codebase have exactly the same weights, we just modified the dictionary in the .pth so that it can be reloaded with the new codebase. Maybe you could compare the outputs with run.sh and run_v0.sh and 
I eyeballed your run and translate scripts and did not see any error, I could also compare your outputs to mine if you send me some IDs that don't work with the new codebase. I guess you also checked that you have no local changes to the codegen or transcoder source code that could explain the difference.

**Comment by wasiahmad** [comment]
- Yes, the performance improvements are expected even we have only 2388 training examples.
- Yes, we ensure there is no overlap in our data and the test data of TransCoder_gfg. [[ref]](https://github.com/wasiahmad/AVATAR/blob/main/data/g4g_fn.py)
- I am no longer looking for the 4-5 points performance boost, it is resolved. Although I don't know how it got resolved.
  - I did compare the output of the two versions of the code and it was mostly increased syntax error. But since the problem is solved now, I didn't dig the issue deeper.
- Yes, the changes I have made should not affect the operation technique. I only made changes to adapt to my repo's file structure.

Thank you once again :)

**Comment by cobolToJava** [comment]
Hi @wasiahmad ,

I am writing to you on behalf of my team, as we are currently working on reproducing Python-to-Java code translation using TransCoder. We came across your successful model reproduction and we believe that your experience and expertise could be of great help to us.

We have a few questions that we hope you can help us with. Firstly, we would like to know the size of the data you used for successful reproduction. Currently, we have access to 50GB of Java and 50GB of COBOL data. Would this be sufficient for reproducing the model?

Secondly, we are curious to know if the data used for MLM training was original or obfuscated data.

Finally, we have noticed that the model filters out a large portion of the training data. Is this a common phenomenon in model training?

Thank you in advance for your help.

Best regards,
Wei
