### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by yazdanbakhsh** [facebookresearch/CodeGen#13]
I am trying to reproduce the results in Transcoder paper. For that I have started with the preprocessing part. For some of the files, I get the following error. I saw that the timeout for `extract_data_for_line` is set to 60 second, hence these timeout exceptions occur. Is this ok or should I extend the timeout for this function?

```
INFO - 08/29/21 22:58:02 - 0:14:58 - Timeout error extracting data
INFO - 08/29/21 23:02:49 - 0:19:45 - Timeout error extracting data
INFO - 08/29/21 23:08:52 - 0:25:48 - Timeout error extracting data
INFO - 08/29/21 23:12:51 - 0:29:47 - Timeout error extracting data
INFO - 08/29/21 23:13:18 - 0:30:14 - Timeout error extracting data
INFO - 08/29/21 23:13:57 - 0:30:53 - Timeout error extracting data
INFO - 08/29/21 23:14:50 - 0:31:46 - Timeout error extracting data
INFO - 08/29/21 23:15:03 - 0:31:59 - Timeout error extracting data
INFO - 08/29/21 23:15:56 - 0:32:52 - Timeout error extracting data
INFO - 08/29/21 23:16:23 - 0:33:18 - Timeout error extracting data
```

**Comment by brozi** [comment]
Hello. 
Each one of these timeouts corresponds to one line in the json file (i.e. code source file in the dataset) that will be ignored because it was not processed fast enough. 
Increasing the timeout would lead to better results since less lines will be ignored but would also make the pipeline slower. If this is happening for your test dataset or for a high ratio of lines in your training dataset, you should probably increase the timeout.

**Comment by brozi** [comment]
Closing this issue. Feel free to reopen if the answer doesn't solve your problem.
