### ISSUE TITLE
Why PythonProcessor is not extending TreeSitterLangProcessor?

### ISSUE THREAD

**Issue by wasiahmad** [facebookresearch/CodeGen#25]
I am curious, why PythonProcessor is not extending TreeSitterLangProcessor? I modified PythonProcessor to extend TreeSitterLangProcessor and found it works. I only checked the `get_tokens_and_types` function for Python.

**Comment by brozi** [comment]
It's only because we already had a working version with the tokenize library and, since the python tokenization is a bit different from that of Java and C++ (keeps the newlines and identation) and it requires a bit of work to make sure that the tokenizers/detokenizers are equivalent. We were thinking of harmonizing it to also use TreeSitter and extend TreeSitterLangProcessor but haven't done it. Feel free to do a pull request if you tested it and it works well.
